### ISSUE TITLE
fjern "nyhet 2020..." og "(c) 2020"?

### ISSUE THREAD

**Issue by flammie** [divvungiellatekno/divvun.no#1]
mye av tilbakemelding vi får kommer fra folk som tror at verktøyene har ikke vart oppdatert sedan 2020, på divvun.no frontsiden det står 2020 to ganger som kanskje skall bli oppdatert eller fjernt?

**Comment by snomos** [comment]
Det er eit bra poeng. Sjølv om vi skal laga nye nettsider, så kan ikkje dei noverande sidene gje inntrykk av at ingen ting har hendt. Det er annan informasjon der òg som er utdatert. Vi må kanskje sjå over alle sidene uansett sjølv om vi lagar nye sider i vår.
